version: "3.7"
services:
  mqtt:
    image: blinkylite/blinky-mqtt:${DOCKER_TAG}
    restart: unless-stopped
    container_name: blinky-mqtt
    user: root
    ports:
      - "${MQTTPORT}:1883"
      - "9001:9001"
    volumes:
      - /home/pi/blinky-box-config/mqtt-auth:/mqtt-auth
networks:
  default:
    name: tunnel
    external: true


