version: "3.7"
services:
  mongo-express:
    image: ${HARDWARE}mongo-express:0.54
    container_name: blinky-mongo-express
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "${EXPRESSPORT}:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${BLINKYLITE_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=blinky-mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=${BLINKYLITE_PASSWORD}
networks:
  default:
    name: tunnel
    external: true

