version: "3.7"
services:
  blinky-MAX31865-trays:
    image: blinkylite/blinky-max31865-trays:${DOCKER_TAG}
    restart: unless-stopped
    container_name: blinky-max31865-trays
#    ports:
#      - "60432:60432"
    environment:
      - BOX=${BOX}
      - TRAYTYPE=blinky-MAX31865
      - MQTTCLIENTID=${BOX}-blinky-MAX31865
      - MQTTSERVERIP=blinky-mqtt
      - MQTTUSERNAME=${BOX}
      - MQTTPASSWORD=${BLINKYPASSWORD}
      - MQTTPORT=1883
      - NODEREDPORT=60432
      - ENABLE_NODERED_EDITOR=0
networks:
  default:
    name: tunnel
    external: true


