version: "3.7"
services:
  blinky-filebrowser:
    image: blinkylite/filebrowser:${DOCKER_TAG}
    restart: unless-stopped
    container_name: blinky-filebrowser
    user: ${uid}:${gid}
    ports:
      - "${PORT}:8080"
    volumes:
      - /home/pi:/srv
networks:
  default:
    name: tunnel
    external: true


