version: "3.7"
services:
  blinky-box:
    image: blinkylite/blinky-box:${DOCKER_TAG}
    restart: unless-stopped
    container_name: blinky-box
#    ports:
#      - "${BLINKYPORT}:60427"
    environment:
      - BOX=${BOX}
      - MONGODBIP=mongodb://admin:${BLINKYLITE_PASSWORD}@blinky-mongo:27017/blinky-lite?retryWrites=true&serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256
      - MQTTCLIENTID=${BOX}
      - MQTTSERVERIP=blinky-mqtt
      - MQTTUSERNAME=${BOX}
      - MQTTPASSWORD=${BLINKYLITE_PASSWORD}
      - MQTTPORT=${MQTTPORT}
      - TELBOT=${TELBOT}
      - TELEGRAM_TIMEOUT=${TELEGRAM_TIMEOUT}
      - JWTKEYSECRET=${JWTKEYSECRET}
      - MAXDBSIZE=${MAXDBSIZE}
      - IPREFWEB=https://www.blinky-lite.se
      - TWOFA=${TWOFA}
      - ENABLEARCHIVE=${ENABLEARCHIVE}
      - NODEREDPORT=60427
      - HTMLSTATICDIR=/data/html-static
      - REQUIREHTTPS=${REQUIREHTTPS}
      - ENABLE_NODERED_EDITOR=${ENABLE_NODERED_EDITOR}
networks:
  default:
    name: tunnel
    external: true


