version: "3.7"
services:
  blinky-ntfy:
    image: blinkylite/blinky-ntfy:${DOCKER_TAG}
    container_name: blinky-ntfy
    command:
      - serve
    environment:
      NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
      NTFY_BASE_URL: ${NTFY_BASE_URL}
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_BEHIND_PROXY: true
      NTFY_ATTACHMENT_CACHE_DIR: /var/lib/ntfy/attachments
      NTFY_ENABLE_LOGIN: true
    volumes:
      - var-lib-ntfy:/var/lib/ntfy
      - var-cache-ntfy:/var/cache/ntfy
      - etc-ntfy:/etc/ntfy
#    ports:
#      - 8080:80
    restart: unless-stopped
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://blinky-ntfy:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
  blinky-ntfy-alarm-service:
    image: blinkylite/blinky-ntfy-alarm-service:${DOCKER_TAG}
    restart: unless-stopped
    container_name: blinky-ntfy-alarm-service
#    ports:
#      - "${NODEREDPORT}:60426"
    environment:
      - BOX=${BOX}
      - MQTTCLIENTID=blinky-ntfy-alarm-service
      - MQTTSERVERIP=blinky-mqtt
      - MQTTUSERNAME=${BOX}
      - MQTTPASSWORD=${BLINKYPASSWORD}
      - MQTTPORT=1883
      - HUB=${HUB}
      - NTFYIP=blinky-ntfy:80
      - NTFYUSERNAME=admin
      - NTFYPASSWORD=${NTFYPASSWORD}
      - NODEREDPORT=60426
      - ENABLE_NODERED_EDITOR=0
    depends_on:
      blinky-ntfy:
        condition: service_healthy
volumes:
  var-cache-ntfy:
    driver: local  
  etc-ntfy:
    driver: local  
  var-lib-ntfy:
    driver: local  
networks:
  default:
    name: tunnel
    external: true


