version: "3.7"
services:
  filebrowser:
    image: blinkylite/filebrowser:${DOCKER_TAG}
    restart: unless-stopped
    container_name: blinky-file
    ports:
      - "${PORT}:80"
    volumes:
      - /home/pi:/srv
networks:
  default:
    name: tunnel
    external: true


