version: "3.7"
services:
  filebrowser:
    image: filebrowser/filebrowser
    restart: unless-stopped
    container_name: blinky-file
    user: 1000:1000
    ports:
      - "${PORT}:80"
    volumes:
      - /home/pi:/srv
networks:
  default:
    name: tunnel
    external: true


