version: "3.7"
services:
  blinky-nginx:
    image: blinkylite/blinky-nginx:${DOCKER_TAG}
    container_name: blinky-nginx
    restart: unless-stopped
    volumes:
      - nginx-confd:/etc/nginx/conf.d
    ports:
      - "80:80"
volumes:
  nginx-confd:
    driver: local  
networks:
  default:
    name: tunnel
    external: true


