version: "3.7"
services:
  blinky-json-echo-trays:
    image: blinkylite/blinky-json-echo-trays:${DOCKER_TAG}
    restart: unless-stopped
    container_name: blinky-json-echo-trays-${TRAY_TYPE}
#    ports:
#      - "${NODEREDPORT}:60437"
    environment:
      - BOX=${BOX}
      - TRAY_TYPE=${TRAY_TYPE}
      - MQTTCLIENTID=${BOX}-${TRAY_TYPE}
      - MQTTSERVERIP=blinky-mqtt
      - MQTTUSERNAME=${BOX}
      - MQTTPASSWORD=${BLINKYPASSWORD}
      - MQTTPORT=1883
      - MQTTHUB=blinky-hub
      - ADMINNAME=admin
      - NODEREDPORT=60437
      - ENABLE_NODERED_EDITOR=${ENABLE_NODERED_EDITOR}
networks:
  default:
    name: tunnel
    external: true


