version: "3.7"
services:
  blinky-alarm-service:
    image: blinkylite/blinky-alarm-service:${DOCKER_TAG}
    restart: unless-stopped
    container_name: blinky-alarm-service
#    ports:
#      - "${NODEREDPORT}:60426"
    environment:
      - BOX=${BOX}
      - MQTTCLIENTID=${BOX}-alarm-service
      - MQTTSERVERIP=${MQTTSERVERIP}
      - MQTTUSERNAME=${MQTTUSERNAME}
      - MQTTPASSWORD=${MQTTPASSWORD}
      - MQTTPORT=1883
      - HUB=${HUB}
      - TELEGRAM_BOT=${TELEGRAM_BOT}
      - NODEREDPORT=60426
      - ENABLE_NODERED_EDITOR=0
networks:
  default:
    name: tunnel
    external: true


