version: "3.7"
services:
  blinky-filebrowser:
    image: blinkylite/filebrowser:${DOCKER_TAG}
    restart: unless-stopped
    container_name: blinky-filebrowser
#    user: 1000:1000
    ports:
      - "${PORT}:8080"
    volumes:
      - /home/pi:/srv
#      - /home/pi/database.db:/database.db
networks:
  default:
    name: tunnel
    external: true


