version: "3.7"
services:
  blinky-alarm-service:
    image: blinkylite/blinky-alarm-service:${DOCKER_TAG}
    restart: unless-stopped
    container_name: ${ALARMBOTNAME}-alarm-service
#    ports:
#      - "${NODEREDPORT}:60426"
    environment:
      - BOX=${BOX}
      - MQTTCLIENTID=${ALARMBOTNAME}-alarm-service
      - MQTTSERVERIP=blinky-mqtt
      - MQTTUSERNAME=${BOX}
      - MQTTPASSWORD=${BLINKYPASSWORD}
      - MQTTPORT=1883
      - HUB=${HUB}
      - TELEGRAM_BOT=${TELEGRAM_BOT}
      - NODEREDPORT=60426
      - ENABLE_NODERED_EDITOR=0
networks:
  default:
    name: tunnel
    external: true


