version: "3.7"
services:
  gantner-iter-tray:
    image: blinkylite/gantner-iter-tray:${DOCKER_TAG}
    restart: unless-stopped
    container_name: gantner-iter-tray-${TRAYNAME}
#    ports:
#      - "${NODEREDPORT}:1880"
    environment:
      - BOX=${BOX}
      - TRAYTYPE=${TRAY}
      - TRAYNAME=${TRAYNAME}
      - MQTTCLIENTID=${MQTTCLIENTID}
      - MQTTSERVERIP=${MQTTSERVERIP}
      - MQTTUSERNAME=${MQTTUSERNAME}
      - MQTTPASSWORD=${MQTTPASSWORD}
      - MQTTPORT=${MQTTPORT}
      - MODBUSIP=${MODBUSIP}
      - MODBUSPORT=${MODBUSPORT}
      - NODEREDPORT=1880
      - ENABLE_NODERED_EDITOR=${ENABLE_NODERED_EDITOR}
networks:
  default:
    name: tunnel
    external: true


