version: "3.7"
  
services:
  web:
    image: blinkylite/ls224controller:${DOCKER_TAG}
    container_name: ${TRAY_TYPE}
    restart: unless-stopped
#    ports:
#      - "60427:60427"
    environment:
      - BOX=${BOX}
      - TRAY_TYPE=${TRAY_TYPE}
      - MQTTCLIENTID=${TRAY_TYPE}
      - MQTTSERVERIP=blinky-mqtt
      - MQTTUSERNAME=${BOX}
      - MQTTPASSWORD=${BLINKYLITE_PASSWORD}
      - MQTTPORT=1883
      - CONTROLLER_IP=${CONTROLLER_IP}
      - CONTROLLER_PORT=7777
      - NODEREDPORT=60427
      - ENABLE_NODERED_EDITOR=1
      - NODE_RED_TITLE=${TRAY_TYPE}
      - HTMLSTATICDIR=/data/html-static/
networks:
  default:
    name: tunnel
    external: true
