version: "3.7"
services:
  mqtt:
    image: blinkylite/blinky-hub-mqtt:${DOCKER_TAG}
    restart: unless-stopped
    container_name: blinky-hub-mqtt
    ports:
      - "${MQTTPORT}:1883"
    volumes:
      - config:/mosquitto/config
networks:
  default:
    name: tunnel
    external: true
volumes:
  config:
    driver: local
    
