version: "3.7"
services:
  jupyter:
    image: blinkylite/jupyter-notebook:5.0-amd64
    container_name: jupyter-notebook
    restart: always
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
networks:
  default:
    name: tunnel
    external: true

